services:

  db:
    image: postgres
    container_name: cites_perdus_db
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    
  seed:
    build: .
    container_name: epopee_seed
    env_file:
      - .env
    command: python3 scripts/seed.py
    restart: "no"
    depends_on:
      db:
        condition: service_healthy

  adminer:
    image: adminer
    container_name: interface_db
    restart: always
    ports:
      - 8080:8080

  app:
    build: .
    container_name: epopee_app
    restart: always
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
  
volumes:
  postgres_data: