name: Deploy

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/md'
      - 'docs/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            if [ ! -d "/home/ubuntu/epopee-des-cites-perdues" ]; then
              git clone https://github.com/SimonGallien/epopee-des-cites-perdues.git /home/ubuntu/epopee-des-cites-perdues
            fi
            cd /home/ubuntu/epopee-des-cites-perdues
            echo "DB_HOST=${{ secrets.DB_HOST }}" > .env
            echo "DB_USER=${{ secrets.DB_USER }}" >> .env
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
            echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
            echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
            git pull origin main
            docker compose -f docker-compose.prod.yml down
            docker compose -f docker-compose.prod.yml up -d --build
            docker compose -f docker-compose.prod.yml run --rm app python scripts/init_db.py
            docker compose -f docker-compose.prod.yml run --rm seed